# config/database.yml

default: &default
  adapter: postgresql
  # Remove "unicode" — let libpq default to UTF8 or specify utf8 explicitly
  # encoding: unicode
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: medi_bridge_development

test:
  <<: *default
  database: medi_bridge_test

production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

